### ISSUE TITLE
ImageSharp naming confusion.

### ISSUE THREAD

**Issue by JimBobSquarePants** [cocosip/DotCommon#1]
I've noticed you're using the name ImageSharp without any reference to The [ImageSharp](https://github.com/SixLabors/ImageSharp) library. This is going to cause a lot of confusion for anyone who find the package on Nuget. Would it be possible to rename the project?

**Comment by cocosip** [comment]
Thank you for your advice， i will fix this problem latter .

**Comment by JimBobSquarePants** [comment]
Thanks! I really appreciate that!

**Comment by cocosip** [comment]
I have rename the project.
 see [commit](https://github.com/cocosip/DotCommon/commit/20c0a3e80564a1fd9b4e255fad00b0b774ad96ae)
